spring:
  profiles:
    active: dev
  application:
    name: bankService
  cloud:
    loadbalancer:
      enabled: false
server:
  port: 8084

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
